language: node_js
node_js:
  - "node"
cache:
  yarn: true
script:
  - yarn test:lint
  - yarn test:ava
  - yarn build && yarn test:lint:package:firefox:v52 || yarn build:firefox:v50 && yarn test:lint:package:firefox:v50
